// Generated by https://quicktype.io

export interface Services {
    services: Service[];
    msg:      string;
}

export interface Service {
    service_state:       boolean;
    _id:                 string;
    service_name:        string;
    service_description: string;
    service_topic:       number;
    service_image:       string;
    __v:                 number;
}

// Generated by https://quicktype.io

export interface Projects {
    projects: Project[];
    msg:      string;
}

export interface Project {
    project_tecnologies: ProjectTecnology[];
    project_state:       boolean;
    _id:                 string;
    project_name:        string;
    project_description: string;
    project_topic:       number;
    project_url:         string;
    __v:                 number;
}

export interface ProjectTecnology {
    _id:       string;
    tech_name: string;
}
